#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";

/**
 * Parses .env file into a key-value map.
 * @param {string} envPath
 * @returns {Record<string, string>}
 */
function parseEnv(envPath) {
  const env = {};
  if (!fs.existsSync(envPath)) return env;
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) continue;
    const idx = trimmed.indexOf("=");
    const key = trimmed.substring(0, idx).trim();
    let val = trimmed.substring(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  }
  return env;
}

/**
 * Detects job files inside app/jobs/ directory.
 * @param {string} jobsDir
 * @returns {string[]} Relative paths to job files.
 */
function detectJobs(jobsDir) {
  if (!fs.existsSync(jobsDir)) return [];
  try {
    return fs
      .readdirSync(jobsDir)
      .filter((f) => f.endsWith(".js") || f.endsWith(".mjs"))
      .map((f) => path.join("app/jobs", f).replace(/\\/g, "/"));
  } catch {
    return [];
  }
}

/**
 * Generates the PM2 ecosystem.config.cjs file for standalone deployments.
 */
function makeEcosystem() {
  const cwd = process.cwd();
  const envPath = path.join(cwd, ".env");
  const outputPath = path.join(cwd, "ecosystem.config.cjs");

  const env = parseEnv(envPath);
  const instances = parseInt(env.PM2_INSTANCES || "1", 10);
  const execMode = instances > 1 ? "cluster" : "fork";
  const appName = (env.TITLE || path.basename(cwd) || "blue-bird")
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, "-");

  const jobsDir = path.join(cwd, "app/jobs");
  const jobs = detectJobs(jobsDir);

  const mainApp = {
    name: appName,
    script: "app/index.js",
    instances,
    exec_mode: execMode,
    node_args: "--env-file=.env",
    env: {
      NODE_ENV: "production",
      DEBUG: "false",
    },
    max_memory_restart: env.PM2_MAX_MEMORY || "512M",
    error_file: "logs/pm2-error.log",
    out_file: "logs/pm2-out.log",
    log_date_format: "YYYY-MM-DD HH:mm:ss",
    autorestart: true,
    watch: false,
  };

  const workerApps = jobs.map((jobFile) => {
    const jobName = path.basename(jobFile, path.extname(jobFile));
    return {
      name: `${appName}-worker-${jobName}`,
      script: jobFile,
      instances: 1,
      exec_mode: "fork",
      node_args: "--env-file=.env",
      env: {
        NODE_ENV: "production",
        DEBUG: "false",
      },
      max_memory_restart: "256M",
      error_file: `logs/pm2-worker-${jobName}-error.log`,
      out_file: `logs/pm2-worker-${jobName}-out.log`,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: true,
      watch: false,
    };
  });

  const allApps = [mainApp, ...workerApps];

  const fileContent = `/**
 * Generated by: npx blue-bird make:ecosystem
 * Deployment mode: ${execMode} (PM2_INSTANCES=${instances})
 *
 * Usage:
 *   pm2 start ecosystem.config.cjs
 *   pm2 reload ecosystem.config.cjs --update-env
 *   pm2 delete ecosystem.config.cjs
 *
 * Recommendations:
 *   - Single instance (PM2_INSTANCES=1): SQLite + memory cache work well standalone.
 *   - Multiple instances (PM2_INSTANCES>1): Use MySQL/PostgreSQL and CACHE_MODE=redis.
 *   - For full production stack with Nginx + Redis: use Docker (npx blue-bird docker start).
 */

module.exports = {
  apps: ${JSON.stringify(allApps, null, 4)}
};
`;

  if (fs.existsSync(outputPath)) {
    console.log(chalk.yellow("[WARN] ecosystem.config.cjs already exists. Overwriting."));
  }

  try {
    fs.mkdirSync(path.join(cwd, "logs"), { recursive: true });
    fs.writeFileSync(outputPath, fileContent, "utf-8");
    console.log(chalk.green(`[OK] Generated ecosystem.config.cjs (${instances} instance(s), mode: ${execMode}).`));

    if (jobs.length > 0) {
      console.log(chalk.cyan(`[INFO] Detected ${jobs.length} worker job(s):`));
      jobs.forEach((j) => console.log(chalk.gray(`       - ${j}`)));
    }

    console.log("");
    console.log(chalk.bold("Next steps:"));
    console.log(chalk.gray("  pm2 start ecosystem.config.cjs"));
    console.log(chalk.gray("  pm2 save"));
    console.log(chalk.gray("  pm2 startup"));

    if (instances > 1) {
      console.log("");
      console.log(chalk.yellow("[WARN] Multiple PM2 instances detected."));
      console.log(chalk.gray("       Ensure CACHE_MODE=redis and a shared database (MySQL/PostgreSQL)."));
      console.log(chalk.gray("       For the best multi-instance production setup, use Docker instead:"));
      console.log(chalk.gray("         npx blue-bird docker start"));
    }
  } catch (err) {
    console.error(chalk.red("[ERROR] Failed to generate ecosystem.config.cjs:"), err.message);
  }
}

makeEcosystem();
